### ISSUE TITLE
Multiple scopes with the same name in router

### ISSUE THREAD

**Issue by williamweckl** [rhazdon/blue_bird#4]
If I have the same scope name in router, api docs generator ignores the second one.

Example:

```elixir
  # Not authenticated Requests
  scope "/", MyApp.Web do
    pipe_through :api
    scope "/auth", Auth do
      post "/sessions", SessionController, :create
    end
  end

  # Authenticated Requests - Ignored by generator
  scope "/", MyApp.Web do
    pipe_through :api_auth
    scope "/auth", Auth do
      get "/user/current", UserController, :current
    end
  end

**Comment by rhazdon** [comment]
Hi @williamweckl,

currently, BlueBird expects that the routes are piped through `:api`. 
See [link to code](https://github.com/rhazdon/blue_bird/blob/master/lib/blue_bird/generator.ex#L43). This is a known issue and is still on the todo list. :D  

I will do this as soon as possible. The idea is to make the respected pipes configureable.

**Comment by williamweckl** [comment]
Hi @rhazdon,

Thanks for your explanation. I had no idea of this hardcoded config. 

By the way, thx for the work done... I was using phoenix_api_docs but your fork is better and up to date. ;)

**Comment by williamweckl** [comment]
@rhazdon I've changed my router to use the pipe_through :api in both scopes and it worked. For me it solved the problem. Feel free to close it if you want.

Thanks again!

**Comment by rhazdon** [comment]
@williamweckl, thank you! :)
