### ISSUE TITLE
Generates request body for url parameters

### ISSUE THREAD

**Issue by woylie** [rhazdon/blue_bird#5]
When you call and log a url with parameters, bluebird will not only include the parameters in the url, but also generate a request body with those parameters, even though no request body was sent in the connection.

Route: `GET /items/:id`

Example test:

```
conn = conn
|> put_req_header("accept", "application/json")
|> conn = get(conn, item_path(conn, :show, 123))

ConnLogger.save(conn)
```

Route in docs: `GET /items/{id}`

Request body according to doc:

```
{
  "id": "123"
}
```

**Comment by rhazdon** [comment]
Hi @woylie,

thanks for report. The issue is solved in v0.1.2.

Best regards
