### ISSUE TITLE
Output is not valid

### ISSUE THREAD

**Issue by woylie** [rhazdon/blue_bird#6]
There are some issues with the generated apib file. Aglio displays the following errors.

> headers is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 12 spaces or 3 tabs (warning code 10)

> message-body asset is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 12 spaces or 3 tabs (warning code 10)

The next error occurs when the response body is a text that includes line breaks:

> dangling message-body asset, expected a pre-formatted code block, indent every of it's line by 12 spaces or 3 tabs (warning code 10)

When a route has no parameters, it will still generate a parameter heading:

> no parameters specified, expected a nested list of parameters, one parameter per list item (warning code 3)

When a route is available with different methods (e.g. `GET /items` and `POST /items`), those routes aren't grouped correctly and we get the following error:

> the resource '/items' is already defined (warning code 2)

**Comment by rhazdon** [comment]
Hey @woylie,

thank you for your report! :)

Fixed with [v0.1.3](https://hex.pm/packages/blue_bird).

Best regards,
Djordje
